version: '3.9'

services:
  app:
    build:
      context: ./server  # Points to the server folder where Dockerfile exists
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"  # Expose FastAPI app port
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-app.rule=Host(`api.localhost`)"
      - "traefik.http.services.fastapi-app.loadbalancer.server.port=8000"
    networks:
      - traefik_network

  next-app:
    build:
      context: ./web-app  # Points to the web-app folder where your Next.js app exists
    container_name: nextjs_app
    ports:
      - "3000:3000"  # Expose Next.js app port
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs-app.rule=Host(`localhost`)"
      - "traefik.http.services.nextjs-app.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
