import type { Metadata } from "next";
import "./globals.css";

import DashboardLayout from '@/components/dashboard-layout'
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Flexidb",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout>{children}

        <Toaster />
        </DashboardLayout>
      </body>
    </html>
  )
}   