import type { Metadata } from "next";
import "./globals.css";

import DashboardLayout from '@/components/dashboard-layout'
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from '@/contexts/auth-context'

export const metadata: Metadata = {
  title: "Flexidb",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DashboardLayout>{children}

          <Toaster />
          </DashboardLayout>
        </AuthProvider>
      </body>
    </html>
  )
}   
